version: 2

macros:
    - name: no_nulls_in_columns
      description: > 
            This macro returns all rows in the specified model where any column contains a NULL value.
            It iterates over all columns in the model and checks if any of them are NULL. 
            The result is a dataset with rows that have NULL values in any column.
      
      arguments:
        - name: model
          type: Relation
          description: >
            The name of the model to check for NULL values. This should be a valid name of dbt model
    
    - name: positive_value
      description: >
            This macro returns rows in a model where a specified column contains value less than 1
            It is also applicable on a single column

      arguments:
        - name: model, column name
          type: Relation
          description: >
            The macro takes in valid dbt model name and the column name in that model to run on 
        
    