version: 2

models:
  - name: src_listings
    description: "Details of airbnb listings"
    columns:
      - name: listing_id
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
        data_type: int64

      - name: listing_url
        description: URL of the listing
        data_type: string
        quote: true

      - name: listing_name
        description: Name of the listing
        data_type: string
        quote: true

      - name: listing_room_type
        description: Type of the room
        data_type: string
        quote: true

      - name: minimum_nights
        data_type: int64
        quote: true

      - name: host_id
        data_type: int64
        quote: true

      - name: listing_price
        data_type: int64
        quote: true

      - name: created_at
        description: Listing created time
        data_type: timestamp
        quote: true

      - name: updated_at
        description: Last updated time of listing
        data_type: timestamp
        quote: true

  - name: src_hosts
    description: "Details of airbnb hosts with listings"
    columns:
      - name: host_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: src_reviews
    description: "Details of airbnb guests reviews on their stay experience "
    columns:
      - name: listing_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: dim_hosts
    columns:
      - name: host_id
        description: Unique host id
        data_type: int64
        quote: true

      - name: host_name
        description: Name of host
        data_type: string
        quote: true

      - name: is_superhost
        description: A superhost is a responsive and well rate host
        data_type: boolean
        quote: true

      - name: created_at
        description: Host created timestamp
        data_type: timestamp
        quote: true

      - name: updated_at
        description: Last updated info about the host
        data_type: timestamp
        quote: true

  - name: dim_listings_cleansed
    description: Attributes about each listing we have
    columns:
      - name: listing_id
        description: Unique listing id
        data_type: int64
        quote: true

      - name: listing_name
        data_type: string
        quote: true

      - name: listing_room_type
        description: Type of the room (apartment, building, house)
        data_type: string
        quote: true

      - name: minimum_nights
        description: Minimum nights a guest has to book for that listing
        data_type: int64
        quote: true

      - name: host_id
        description: Unique id of the assoicated host with the listing
        data_type: int64
        quote: true

      - name: price
        description: Per night price (Euros) for the stay
        data_type: numeric
        quote: true

      - name: created_at
        description: Listing created timestamp
        data_type: timestamp
        quote: true

      - name: updated_at
        description: Last updated info about the listing
        data_type: timestamp
        quote: true

  - name: dim_listings_with_hosts
    description: Joined table Dim_Listings and Dim_Hosts to get a combined dimension table about each listing id
    columns:
      - name: listing_id
        data_type: int64
        quote: true

      - name: listing_name
        data_type: string
        quote: true

      - name: listing_room_type
        data_type: string
        quote: true

      - name: minimum_nights
        data_type: int64
        quote: true

      - name: price
        data_type: numeric
        quote: true

      - name: host_id
        data_type: int64
        quote: true

      - name: host_name
        data_type: string
        quote: true

      - name: is_superhost
        data_type: boolean
        quote: true

      - name: created_at
        data_type: timestamp
        quote: true

      - name: updated_at
        data_type: timestamp
        quote: true

  - name: fct_reviews
    description: FACT table recording reviews posted by staying guests in the airbnb listings
    columns:
      - name: listing_id
        data_type: int64
        quote: true

      - name: review_date
        data_type: timestamp
        quote: true

      - name: reviewer_name
        data_type: string
        quote: true

      - name: review_text
        description: Text of the review message written by the guest
        data_type: string
        quote: true

      - name: sentiment
        description: "Kind of sentiment of the text: 'Positive' , 'Negative' or 'Neutral'"
        data_type: string
        quote: true
  - name: mart_fullmoon_reviews
    description: Data mart table based on fct_reviews having additional column of whether the night was full moon or not
    columns:
      - name: listing_id
        description: Listing id of the listing being reviewed by the guest
        data_type: int64
        quote: true
      - name: review_date
        description: Date of review posted by the guest
        data_type: timestamp
        quote: true
      - name: reviewer_name
        data_type: string
        quote: true
      - name: review_text
        data_type: string
        quote: true
      - name: sentiment
        data_type: string
        quote: true
      - name: is_full_moon
        description: If the night of the stay was a full moon night or not. We created a join with full moon dates seed file and joined on review date by incrementing full moon date by 1 because reviews are posted on next day of stay usually
        data_type: string
        quote: true

snapshots:
  - name: scd_raw_listings
    description: Snapshot table to track changes in Raw_Listings table. Any time a field in raw_listings table changes, we'll have another record populated for that listing id with a new update_at field. This enables us to keep a track of historic changes taking palce of each listing id
    columns:
      - name: id
        description: Listing ID
        data_type: int64
        quote: true
      - name: listing_url
        data_type: string
        quote: true
      - name: name
        data_type: string
        quote: true
      - name: room_type
        data_type: string
        quote: true
      - name: minimum_nights
        data_type: int64
        quote: true
      - name: host_id
        data_type: int64
        quote: true
      - name: price
        data_type: int64
        quote: true
      - name: created_at
        data_type: timestamp
        quote: true
      - name: updated_at
        description: Last updated time of listing
        data_type: timestamp
        quote: true
      - name: dbt_scd_id
        description: Internally created dbt hashed ID
        data_type: string
        quote: true
      - name: dbt_updated_at
        data_type: timestamp
        quote: true
      - name: dbt_valid_from
        description: For original record  dbt_valid_from= 'created_at' . For new record dbt_valid_from= 'updated_at'
        data_type: timestamp
        quote: true
      - name: dbt_valid_to
        description: If there is no update on the listing, then for original record  dbt_valid_to= 'null' . If there is change, then for original record dbt_valid_to= 'updated_at' and new record dbt_valid_to = null
        data_type: timestamp
        quote: true