
version: 2

models:
  - name: src_listings
    description: "Details of airbnb listings"
    columns:
      - name: listing_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
